name: Build for Release

on:
  release:
    types: [published, prereleased]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Echo Tag
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF